// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/tracking.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TrackingServerClient is the client API for TrackingServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackingServerClient interface {
	GetCountAd(ctx context.Context, in *IdAdTracked, opts ...grpc.CallOption) (*Count, error)
	IncrementCount(ctx context.Context, in *IdAdTracked, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type trackingServerClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackingServerClient(cc grpc.ClientConnInterface) TrackingServerClient {
	return &trackingServerClient{cc}
}

func (c *trackingServerClient) GetCountAd(ctx context.Context, in *IdAdTracked, opts ...grpc.CallOption) (*Count, error) {
	out := new(Count)
	err := c.cc.Invoke(ctx, "/proto.TrackingServer/GetCountAd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingServerClient) IncrementCount(ctx context.Context, in *IdAdTracked, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.TrackingServer/IncrementCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackingServerServer is the server API for TrackingServer service.
// All implementations must embed UnimplementedTrackingServerServer
// for forward compatibility
type TrackingServerServer interface {
	GetCountAd(context.Context, *IdAdTracked) (*Count, error)
	IncrementCount(context.Context, *IdAdTracked) (*emptypb.Empty, error)
	mustEmbedUnimplementedTrackingServerServer()
}

// UnimplementedTrackingServerServer must be embedded to have forward compatible implementations.
type UnimplementedTrackingServerServer struct {
}

func (UnimplementedTrackingServerServer) GetCountAd(context.Context, *IdAdTracked) (*Count, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountAd not implemented")
}
func (UnimplementedTrackingServerServer) IncrementCount(context.Context, *IdAdTracked) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrementCount not implemented")
}
func (UnimplementedTrackingServerServer) mustEmbedUnimplementedTrackingServerServer() {}

// UnsafeTrackingServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackingServerServer will
// result in compilation errors.
type UnsafeTrackingServerServer interface {
	mustEmbedUnimplementedTrackingServerServer()
}

func RegisterTrackingServerServer(s grpc.ServiceRegistrar, srv TrackingServerServer) {
	s.RegisterService(&TrackingServer_ServiceDesc, srv)
}

func _TrackingServer_GetCountAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdAdTracked)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServerServer).GetCountAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TrackingServer/GetCountAd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServerServer).GetCountAd(ctx, req.(*IdAdTracked))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingServer_IncrementCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdAdTracked)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServerServer).IncrementCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TrackingServer/IncrementCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServerServer).IncrementCount(ctx, req.(*IdAdTracked))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackingServer_ServiceDesc is the grpc.ServiceDesc for TrackingServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackingServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TrackingServer",
	HandlerType: (*TrackingServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCountAd",
			Handler:    _TrackingServer_GetCountAd_Handler,
		},
		{
			MethodName: "IncrementCount",
			Handler:    _TrackingServer_IncrementCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tracking.proto",
}
