// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/ad.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdServerClient is the client API for AdServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdServerClient interface {
	CreateAd(ctx context.Context, in *AdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAd(ctx context.Context, in *IdAd, opts ...grpc.CallOption) (*AdResponse, error)
	ServeAd(ctx context.Context, in *IdAd, opts ...grpc.CallOption) (*Ad, error)
}

type adServerClient struct {
	cc grpc.ClientConnInterface
}

func NewAdServerClient(cc grpc.ClientConnInterface) AdServerClient {
	return &adServerClient{cc}
}

func (c *adServerClient) CreateAd(ctx context.Context, in *AdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/proto.AdServer/CreateAd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adServerClient) GetAd(ctx context.Context, in *IdAd, opts ...grpc.CallOption) (*AdResponse, error) {
	out := new(AdResponse)
	err := c.cc.Invoke(ctx, "/proto.AdServer/GetAd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adServerClient) ServeAd(ctx context.Context, in *IdAd, opts ...grpc.CallOption) (*Ad, error) {
	out := new(Ad)
	err := c.cc.Invoke(ctx, "/proto.AdServer/ServeAd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdServerServer is the server API for AdServer service.
// All implementations must embed UnimplementedAdServerServer
// for forward compatibility
type AdServerServer interface {
	CreateAd(context.Context, *AdRequest) (*emptypb.Empty, error)
	GetAd(context.Context, *IdAd) (*AdResponse, error)
	ServeAd(context.Context, *IdAd) (*Ad, error)
	mustEmbedUnimplementedAdServerServer()
}

// UnimplementedAdServerServer must be embedded to have forward compatible implementations.
type UnimplementedAdServerServer struct {
}

func (UnimplementedAdServerServer) CreateAd(context.Context, *AdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAd not implemented")
}
func (UnimplementedAdServerServer) GetAd(context.Context, *IdAd) (*AdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAd not implemented")
}
func (UnimplementedAdServerServer) ServeAd(context.Context, *IdAd) (*Ad, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServeAd not implemented")
}
func (UnimplementedAdServerServer) mustEmbedUnimplementedAdServerServer() {}

// UnsafeAdServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdServerServer will
// result in compilation errors.
type UnsafeAdServerServer interface {
	mustEmbedUnimplementedAdServerServer()
}

func RegisterAdServerServer(s grpc.ServiceRegistrar, srv AdServerServer) {
	s.RegisterService(&AdServer_ServiceDesc, srv)
}

func _AdServer_CreateAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServerServer).CreateAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AdServer/CreateAd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServerServer).CreateAd(ctx, req.(*AdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdServer_GetAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdAd)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServerServer).GetAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AdServer/GetAd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServerServer).GetAd(ctx, req.(*IdAd))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdServer_ServeAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdAd)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdServerServer).ServeAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AdServer/ServeAd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdServerServer).ServeAd(ctx, req.(*IdAd))
	}
	return interceptor(ctx, in, info, handler)
}

// AdServer_ServiceDesc is the grpc.ServiceDesc for AdServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AdServer",
	HandlerType: (*AdServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAd",
			Handler:    _AdServer_CreateAd_Handler,
		},
		{
			MethodName: "GetAd",
			Handler:    _AdServer_GetAd_Handler,
		},
		{
			MethodName: "ServeAd",
			Handler:    _AdServer_ServeAd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ad.proto",
}
